### ISSUE TITLE
Runtastic backend returns an error if more than 420 activities are requested

### ISSUE THREAD

**Issue by timoschlueter** [timoschlueter/php-runtastic#11]
As mentioned in #10 and #8, there seems to be a problem with the Runtastic backend. Through my first (and not really deep) analysis i found out that the backend is only able to return a maximum of 420 activities. 

I committed a workarround in 7e3d83e7444c71ef5af92a57cfd3e6630d45db95 by limitting the number of requested activities to 420 and sorting them by ID to get the latest ones. 

To resolve this issue, we should implement a paging-algorithm, since i doubt that Runtastic will back off from their introduced "rate limit".

**Comment by timoschlueter** [comment]
A user just sent me code for the paging-mechanism to implement into the class (via mail). 
But i am trying to convince him to create pull request for this - for reasons of better documentation. :)
Either way, we should have a solution for the limitation very soon.

**Comment by mgarciadelojo** [comment]
Is there any chance to send me the code so I can take a look on it and create a pull request? I've been working a lot with your library and I find it awesome!

**Comment by timoschlueter** [comment]
I created a new branch for testing the code. Unfortunately, i don't have the time for tests right now but feel free to test it and create a pull request out of it :)
Its de6880563cd1a1b56eb8a2d1738164681d550616 in the "pagination" branch.

**Comment by mgarciadelojo** [comment]
Allright :) thank you very much. I'll test it with my account and let you know soon!

**Comment by timoschlueter** [comment]
Have you been able to test the changes yet, @mgarciadelojo? :)

**Comment by mgarciadelojo** [comment]
Sorry, for not keeping you up-to-date. Yes, I tested it but it doesn't work well (at least as I expected) because it doesn't fetch an account I have with 400+ runs...

I have a patch to solve it, but changes all the structure of your code. If you want, I can create a Pull Request in order to let you check it out :)

Cheers

**Comment by timoschlueter** [comment]
Sure, create a pull request!
As long as it helps keeping this repo alive, i dont mind if you change all of my code. :)

**Comment by mgarciadelojo** [comment]
Ok, I am glad to hear this from you.

Give me a few days to optimize the code to PSR2 and I’ll create the Pull Request. I am happy to contribute to this repo, because I have used your code almost every day at work :)

Cheers

**Comment by mgarciadelojo** [comment]
I didn’t forget I have to create the pull-request. I’ll do on vacations :)

Cheers

**Comment by timoschlueter** [comment]
Take your time, @mgarciadelojo. 
Merry X-mas. :)

**Comment by mgarciadelojo** [comment]
Thanks @timoschlueter!!

Here you can check out my changes. When I finish them I'll create the pull request. I am testing it with some users I have access to in order to make sure it's working fine :)

https://github.com/mgarciadelojo/php-runtastic

In this version I am using Psr-4 for autoloading. It would break backwards compatibility but users could import the class using "use" instead of "include" or "require".

Happy new year!!

**Comment by mgarciadelojo** [comment]
Hi @timoschlueter,

I am very sorry for the delay, but, you know... Christimas, family, vacations... I had no time until now to create the Pull Request, which you can see here: https://github.com/timoschlueter/php-runtastic/pull/18

I am very happy to contribute to this repo since I have worked with your library for a long time.

Comments are welcome! :)

Cheers!

**Comment by timoschlueter** [comment]
Issue has been fixed in pull request #18.
